# Generated by Django 3.1.4 on 2020-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_auto_20201207_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.TextField(default='<2020-12-26T12:00:00,0>'),
        ),
    ]
