# Generated by Django 3.1.4 on 2020-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20201208_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.TextField(default='<2020-12-8T20:41:00,0>'),
        ),
    ]
