# Generated by Django 3.1.4 on 2020-12-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_auto_20201208_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-score']},
        ),
    ]
