# Generated by Django 3.1.4 on 2020-12-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ques_num', models.PositiveIntegerField(default=0, verbose_name='question number')),
                ('answer', models.CharField(max_length=200)),
                ('asset', models.URLField(max_length=500, verbose_name='assets')),
            ],
        ),
    ]
