# Generated by Django 3.1.4 on 2020-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesAns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_num',
            field=models.PositiveIntegerField(default=0, verbose_name='question number'),
        ),
    ]
